# Development-specific settings.
development:
  PORT: 8080
  KEY: './certs/server.key'
  CRT: './certs/server.crt'
  HUBSPOT_ID: 2661178
  HUBSPOT_API_KEY: 2b83f1c0-1e7a-4ffd-b24e-7c49a0554e0c
  HUBSPOT_PIPELINE_ID: 33eefdb-1801-40aa-9640-76dc1106d927
  HUBSPOT_PARTIAL_PAYMENT_STAGE_ID: 112829
  HUBSPOT_FULL_PAYMENT_STAGE_ID: 112830
# Production-specific settings.
production:
  PORT: 443
  KEY: './certs/server.key'
  CRT: './certs/server.crt'

